export interface Eye {
    image_name: string,
    table_1: number,
    table_2: number,
    table_3: number,
    table_4: number,
    table_5: number,
    table_6: number,
    table_7: number,
    table_8: number,
    table_9: number,
    table_10: number,
    table_11: number,
    table_12: number,
    table_13: number,
    eye_side: number,
}